services:
  # Ваше NestJS приложение
  api:
    build: .
    container_name: nest_rag_app
    restart: always
    env_file:
      - .env.development
    environment:
      - QDRANT_URL=http://qdrant:6333  # Теперь используем имя сервиса!
      # Другие переменные из вашего .env
    depends_on:
      - qdrant
    volumes:
      - ./data:/app/data:ro
      - ./documents:/app/documents:ro
    networks:
      - rag_network

  # База данных Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - ./storage:/qdrant/storage:z
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge
